export const initialDetails = [
    { title: "Project", value: "", key: 'name' },
    { title: "Client Name", value: "", key: 'client_name' },
    { title: "Department Name", value: "", key: 'department_name' },
    { title: "Project In State", value: "", key: 'state' },
    { title: "Project Under Scheme", value: "", key: 'scheme' },
    { title: "Project Under Scheme Other", value: "", key: 'scheme_other' },
    { title: "Project Value", value: "", key: 'value' },
    { title: "Project Value Currency", value: "", key: 'value_currency' },
    { title: "Project Brief", value: "", key: 'brief' },
    { title: "No Of School", value: "", key: 'number_of_schools' },
    { title: "No Of HD", value: "", key: 'number_of_hd' },
    { title: "No Of TD", value: "", key: 'number_of_td' },
    { title: "No Of Control Total", value: "", key: 'number_of_control_total' },
    { title: "No Of Zonal Coordinator", value: "", key: 'number_of_zonal_coordinator' },
    { title: "No Of District Coordinator", value: "", key: 'number_of_district_coordinator' },
    { title: "No Of School Coordinator", value: "", key: 'number_of_school_coordinator' },
    { title: "Manpower SLA Days", value: "", key: 'manpower_sla_days' },
    { title: "Manpower Penalty Per Day", value: "", key: 'manpower_penalty_per_day' },
    { title: "Hardware SLA Days", value: "", key: 'hardware_sla_days' },
    { title: "Hardware Penalty Per Day", value: "", key: 'hardware_penalty_per_day' },
];